controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

product:
    path: /products
    controller: App\Controller\ProductController::index

app_form:
    path: /form
    methods: [GET, POST]
    controller: App\Controller\FormController::index

command:
    path: /command
    controller: App\Controller\CommandController::index
